title: Үздік GitHub
logo: /assets/img/uzdik-logo.png
show_downloads: false
theme: jekyll-theme-minimal

social:
  type:  Uzdik BILIM ARNA # Person or Organization (defaults to Person)
  name:  Yergali Berdibayev # If the user or organization name differs from the site's name
  links:
    - "https://www.youtube.com/Uzdik"
    - "https://t.me/uzdik_bilim"
    - "https://instagram.com/uzdik.bilim"
    - "https://www.facebook.com/uzdik.bilim"
    

