title: Uzdik GitHub
logo: /assets/img/uzdik-logo.png
descriptoin: Uzdik Bilim Alga!gs jgslkfgjs glsjdfkg jsjfj s;ljfg kjskfjgks;jfkg; jskl;jfgkjsf;jgs;jfgljsdflgsdfg  
#show_downloads: true
theme: jekyll-theme-minimal
