title: Үздік GitHub
logo: /assets/img/uzdik-logo.png
show_downloads: false
theme: jekyll-theme-minimal

header_navigation:
  - title: Documentation
    url: /docs/

  - title: Themes
    url: https://desiredpersona.com/themes/

  - title: About
    url: /about/

  - title: Blog
    url: /archive/

  - title: Contact
    url: mailto:you@example.com

footer_navigation:
  - title: privacy
    url: /privacy/

  - title: terms
    url: /terms/

