title: Үздік GitHub
logo: /assets/img/uzdik-logo.png
show_downloads: false
theme: jekyll-theme-minimal

header_pages:
  - Home: /
  - About: /about
  - Contact: /contact

social_links:
  - name: YouTube
    url: https://www.youtube.com/Uzdik
  - name: Telegram
    url: https://t.me/uzdik_bilim
  - name: Facebook
    url: https://www.facebook.com/uzdik.bilim


